/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lcj_mytestprojects_JniDemo */

#ifndef _Included_com_example_lcj_mytestprojects_JniDemo
#define _Included_com_example_lcj_mytestprojects_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lcj_mytestprojects_JniDemo
 * Method:    getJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lcj_mytestprojects_JniDemo_getJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
